### ISSUE TITLE
GitHub Pages environments for all languages and default

### ISSUE THREAD

**Issue by maehr** [CollectionBuilder/cb-translate#8]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

I'd like to build and deploy previews for all available languages from [cb-translate/main](https://github.com/CollectionBuilder/cb-translate/tree/main) using GitHub Pages as described in https://collectionbuilder.github.io/cb-docs/docs/walkthroughs/csv-walkthrough/
For example
https://collectionbuilder.github.io/cb-translate.en
https://collectionbuilder.github.io/cb-translate.es
https://collectionbuilder.github.io/cb-translate.de
https://collectionbuilder.github.io/cb-translate.default

PS: @evanwill I'd need more permissions to setup the environments.

### What type of pull request would this be?

Enhancement

**Comment by maehr** [comment]
@evanwill shall I set up the three previews?

**Comment by evanwill** [comment]
@maehr so would we set up a github action in this cb-translate repository that builds out all three automatically? Or are these separate demo repositories? (or a separate demo repository that builds all three?)

**Comment by maehr** [comment]
I'd like to set up different environments for this repo as documented in https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment

**Comment by evanwill** [comment]
In the other CB repositories we generally build the demo site out of a `demo-site` branch so that it can have separate metadata and content from the `main`. Would all three build from one branch, or are there separate branches, or direct from main?

My concern is just not adding too much complication to the main to make it as simple as possible for people using it as a template. If folks click the "use this template" button, it should work as expected, and not have to like turn off building the demo sites and delete a github action. So if we could trigger the build only on a `demo-site` branch or something like that (rather than on `main`), it might help avoid confusion for people using the template.

**Comment by evanwill** [comment]
p.s. @maehr I updated your permissions
